### ISSUE TITLE
自定义的动漫能够添加自定义观看网址

### ISSUE THREAD

**Issue by flyinclouds** [linyi102/anime_footmark#1]
希望能够添加自定义的观看网址，每次想看都可以打开漫迹，然后快速打开对应的网址观看。PS：最好添加的自定义网址还能够备份。一下提了两个需求，有点贪心(≧∇≦)

**Comment by flyinclouds** [comment]
发现在第一集里面添加笔记完美解决

**Comment by linyi102** [comment]
> 发现在第一集里面添加笔记完美解决

未来会提供修改动漫信息的功能，这样就能直接访问自定义的网址了
