### ISSUE TITLE
[Enhancement] 对于空笔记的处理

### ISSUE THREAD

**Issue by SkyNet-PKN** [linyi102/anime_footmark#12]
在选集页面点击某个集数进入该集笔记页面后：

![1](https://github.com/user-attachments/assets/eef438ad-a090-4a73-a92b-9490be7f8115)

![2](https://github.com/user-attachments/assets/61067278-e827-46a9-97d4-9b577156ffa1)

如果此时直接退出，点击右侧菜单会发现该菜单的样式是“该集存在笔记”的样式：

![3](https://github.com/user-attachments/assets/e98f4361-0713-488e-b378-4a101aba9fcc)

然而此时在笔记界面并不能找到该空笔记，总览界面的笔记计数也不会增加。

因此这样会产生很多因误触而导致的“幽灵笔记”。

*经测试，创建非空笔记后，又将其内容全部删除也会导致上述情况。*

而“评价”页面则不会出现这种情况，如果创建空评价再退出，则会留一个内容为“什么都没有写”的评价，建议将空笔记的逻辑改为与空评价一致。

**Comment by linyi102** [comment]
感谢反馈！其实空笔记和空评价是完全一样的逻辑，查询评价列表和统计数量的时候都会过滤掉空的笔记和评价。空笔记也完全可以当作不存在，唯一的不同之处是点击空笔记后不需要再进行创建，可以直接编辑。请问你是想要在退出空笔记页面的时候自动进行删除吗？

**Comment by SkyNet-PKN** [comment]
我个人觉得可能空笔记自动删除会好一点，不然在选集页可能会感觉有些地方有笔记有些地方没笔记但点进去都是空的。
另外虽然我不太清楚底层实现，但我猜这样的空笔记实际上是计入存档的？因此将空笔记直接删掉也是一个更优的选择。
