### ISSUE TITLE
[Enhancement] 对于标题编辑的处理（win）

### ISSUE THREAD

**Issue by emptylight370** [linyi102/anime_footmark#14]
在Windows上，默认标题占据的空间比较大，是不是可以通过点击标题文本来进入标题编辑界面？
比如点击默认的（第 1 集）这个部分来进入标题编辑。
并且标题没有换行，又是否可以通过输入换行触发保存当前标题？

**Comment by linyi102** [comment]
感谢反馈！这个方式有个问题，现在对话框里有个隐藏默认标题的开关，比如点击第 1 集，默认标题不应该被修改，只能配置显示或隐藏，然后在后面添加自定义的标题。这种想不到有什么好的方式展示出来

**Comment by emptylight370** [comment]
对默认标题和自定义标题的文本都添加进入编辑界面的事件呢？点击到这个文本就相当于点开菜单进入标题编辑按钮。
（就是为菜单里的编辑标题的按钮添加一个快捷方式这样的）

**Comment by linyi102** [comment]
这个可以。下个版本会加上
