### ISSUE TITLE
建议可以按第一集的播放时间来排序

### ISSUE THREAD

**Issue by 610364023** [linyi102/anime_footmark#2]
我想把我豆瓣上的几百条全部移过来，如果要按原来的时间线排的话就必须从最后一个开始加，如果中途错了要改的话，那被改的那个就会跑到第一个去，整个时间线就会乱，加上按播放时间排序就可以随便修改了

**Comment by linyi102** [comment]
> 我想把我豆瓣上的几百条全部移过来，如果要按原来的时间线排的话就必须从最后一个开始加，如果中途错了要改的话，那被改的那个就会跑到第一个去，整个时间线就会乱，加上按播放时间排序就可以随便修改了

你的意思是要按照首播时间来排序吗？点击收藏页右上角的第一个按钮是可以指定按照首播时间进行排序的呀

**Comment by 610364023** [comment]
> > 我想把我豆瓣上的几百条全部移过来，如果要按原来的时间线排的话就必须从最后一个开始加，如果中途错了要改的话，那被改的那个就会跑到第一个去，整个时间线就会乱，加上按播放时间排序就可以随便修改了
> 
> 你的意思是要按照首播时间来排序吗？点击收藏页右上角的第一个按钮是可以指定按照首播时间进行排序的呀

不是首播时间，我指的是第一集手动标的时间，也就是观看时间，像历史里的时间线一样排序
![IMG_20230415_045136](https://user-images.githubusercontent.com/45279039/232152519-40605842-ea49-4263-b070-7192766fabc3.jpg)

**Comment by linyi102** [comment]
@610364023 我明白你的意思了，下个版本会提供这个功能！
