### ISSUE TITLE
有个设计上的问题，Win端的不合理设计

### ISSUE THREAD

**Issue by YsLtr** [linyi102/anime_footmark#3]
![image](https://github.com/linyi102/anime_trace/assets/130123551/4641af37-7942-4006-847e-2cd562c544d9)
Win端的这个下拉还原，原本应该是设计在手机端的，而在win端并没有下拉的功能，因此这个功能在win端没有用处，至少加个刷新按钮之类的。

**Comment by linyi102** [comment]
目前鼠标是支持下拉的，你试一下

**Comment by linyi102** [comment]
@YsLtr 鼠标按住左键可以下拉，你试试

**Comment by YsLtr** [comment]
> @YsLtr 鼠标按住左键可以下拉，你试试

我试了，不行捏
1.10.3版本
系统是win11 22H2 22621.2861

**Comment by linyi102** [comment]
@YsLtr 有没有开启下拉还原呀？开启后才可以下拉的

**Comment by YsLtr** [comment]
> @YsLtr 有没有开启下拉还原呀？开启后才可以下拉的

抱歉这么久才回复，确实是下拉还原没有开😂。
不过我还是觉得Windows端应该设计为使用快捷键的这种方式，用下拉总觉得不合逻辑，像在用安卓模拟器。

**Comment by linyi102** [comment]
@YsLtr 确实是不符合桌面端习惯，快捷键好像也不太合适，我之后想想有没有更好的方法吧，感谢反馈！
