### ISSUE TITLE
[Enhancement] win端的时间设置功能

### ISSUE THREAD

**Issue by emptylight370** [linyi102/anime_footmark#7]
Windows端的时间设置现有两种方案，一是使用右侧的日历和时钟，二是使用左侧的按钮进入数字编辑模式。
在直接填写日期的时候，是使用年/月/日字符串的形式，在直接填写时间的时候，又是两个框里面填写数字，设计上表现的很割裂，同时也不好编辑。另，时间的输入框内文字高度高于输入框高度，可以滚轮上下滚动。
这里我想到一种改进方向，将日期的年月日分开三个输入框，像时间一样，同时将输入框调整为数字，（或许可以通过滚轮上下滚动调整数字（Flutter做得到吗）（看起来是flutter写的））。
不能像网页的数字输入框一样通过滚轮调整数字的话也可以尝试在聚焦输入框的时候选中里面的内容，省去删除修改的过程。

**Comment by linyi102** [comment]
@lingfengyu-dreaming 你好，上下滚动选择是可以实现的，风格上也确实更统一，下个版本会进行优化，感谢反馈！
