### ISSUE TITLE
[Bug] 在PC端，迁移动漫封面预览问题

### ISSUE THREAD

**Issue by emptylight370** [linyi102/anime_footmark#8]
在迁移封面时，如果点入了查看新封面，就会跳转进入全屏的查看器窗口。在这个窗口里面，在图片加载失败的时候，是没有返回按钮的。尤其是迁移bangumi的时候尤为明显，因为很容易加载封面失败。这时候只能重启应用。
![image](https://github.com/linyi102/anime_trace/assets/61617417/e01bdff3-dfed-4dd5-9ba6-0da1275cebfe)

**Comment by linyi102** [comment]
@lingfengyu-dreaming 你好，上个版本虽然修复了这个问题，但是这个地方我忘记处理了，下版本会修复这个问题，感谢提醒！
